### ISSUE TITLE
UnboundLocalError: local variable 'oL' referenced before assignment

### ISSUE THREAD

**Issue by fepegar** [MIC-DKFZ/niicat#3]
```python-traceback
$ niicat t1.nii.gz                                                                                                        ✓  29% (0:52) 🔋  00:42:40
Traceback (most recent call last):
  File "/Users/fernando/miniconda3/envs/episurg/bin/niicat", line 50, in <module>
    main()
  File "/Users/fernando/miniconda3/envs/episurg/bin/niicat", line 46, in main
    plot(args.nifti_file, dpi=args.dpi)
  File "/Users/fernando/miniconda3/envs/episurg/lib/python3.6/site-packages/niicat/plotter.py", line 248, in plot
    return _plot_nifti_preview(iFile, return_fig=return_fig, dpi=dpi)
  File "/Users/fernando/miniconda3/envs/episurg/lib/python3.6/site-packages/niicat/plotter.py", line 159, in _plot_nifti_preview
    plt.text(-10, mY + 5, oL, fontsize=9, color='red')  # Label on left side
UnboundLocalError: local variable 'oL' referenced before assignment
```

You might want to check [nibabel docs](https://nipy.org/nibabel/image_orientation.html) for some high-level utilities to get image orientation.

**Comment by fepegar** [comment]
Orientation info from image header:
```
In [5]: nii.get_qform()
Out[5]:
array([[  0.        ,   0.        ,   1.        , -82.6807251 ],
       [ -1.        ,   0.        ,   0.        , 132.33735657],
       [  0.        ,  -1.        ,   0.        , 102.21686554],
       [  0.        ,   0.        ,   0.        ,   1.        ]])

In [6]: nii.get_sform()
Out[6]:
array([[ -0.        ,   0.        ,   1.        , -82.6807251 ],
       [ -1.        ,  -0.        ,  -0.        , 132.33735657],
       [  0.        ,  -1.        ,   0.        , 102.21686554],
       [  0.        ,   0.        ,   0.        ,   1.        ]])
```

**Comment by wasserth** [comment]
`nib.aff2axcodes(image.affine)` gives different results unfortunately. But I updated the code. Now this error should not occur anymore.
